feature: expose prometheus metrics
TwiN/aws-eks-asg-rolling-update-handler pull request #24
Opened 2022-04-21 08:16 UTC by someone-stole-my-name

This allows users to get insights about what is the handler doing without having to parse logs by themselves.

2022-04-26 01:22 UTC, TwiN requested changes
Some small suggestions, but aside from that, excellent work!
Thank you for contributing :)

2022-04-26 01:22 UTC, TwiN commented on config/config.go
> +
```suggestion
	if metricsPort := os.Getenv(EnvMetricsPort); len(metricsPort) == 0 {
		log.Printf("Environment variable '%s' not specified, defaulting to 8080", EnvMetricsPort)
		cfg.MetricsPort = 8080
	} else {
		port, err := strconv.Atoi(metricsPort)
		if err != nil {
			return fmt.Errorf("invalid value for '%s': %s", EnvMetricsPort, err)
		}
		cfg.MetricsPort = port
	}
	if metrics := strings.ToLower(os.Getenv(EnvMetrics)); len(metrics) != 0 {
		cfg.Metrics = true
	}
```
Just to clear up the empty lines

2022-04-26 01:22 UTC, TwiN commented on metrics/metrics.go
> +			Help:      "The total errors",
```suggestion
			Help:      "The total number of errors",
```

2022-04-26 01:22 UTC, TwiN commented on metrics/metrics.go
> +
```suggestion
	m.register()
```

2022-05-31 07:21 UTC, someone-stole-my-name commented
I've made all changes and squashed.

2022-06-01 03:29 UTC, TwiN requested changes
I'm so sorry for the delay, I've been very busy 😔

2022-06-01 03:29 UTC, TwiN commented on README.md
> +All the metrics are prefixed with `rolling_update_handler`.
Can you just prefix the metrics in the table with that instead? It'll make searching using GitHub easier

2022-06-01 03:29 UTC, TwiN commented on main.go
>  	return HandleRollingUpgrade(kubernetesClient, ec2Service, autoScalingService, autoScalingGroups)
Can you move `metrics.Server.NodeGroups.WithLabelValues().Set(float64(len(autoScalingGroups)))` inside `HandleRollingUpgrade`?

2022-06-01 03:29 UTC, TwiN commented on main.go
>  	}
Can you move this `metrics.Server.Errors.Inc()` to the parent function instead? That way you won't have to do it both here, on line 80 and on line 105 of the same file.

2022-06-02 03:56 UTC, TwiN approved these changes

2022-06-02 03:56 UTC, TwiN commented
Awesome work, thank you for the contribution!

2022-06-02 03:57 UTC, merged

2022-06-07 21:57 UTC, TwiN commented
Released in [v1.4.0](https://github.com/TwiN/aws-eks-asg-rolling-update-handler/releases/tag/v1.4.0)